# Generated by Django 2.2.18 on 2021-07-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_auto_20191018_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='sensitivity',
            field=models.IntegerField(blank=True, choices=[(1, 'Sensitive'), (2, 'Private non-sensitive'), (3, 'Public non-sensitive')], null=True),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='sensitivity',
            field=models.IntegerField(blank=True, choices=[(1, 'Sensitive'), (2, 'Private non-sensitive'), (3, 'Public non-sensitive')], null=True),
        ),
    ]
